### ISSUE TITLE
Breaking the 8 Players Limit on SA

### ISSUE THREAD

**Issue by ifarbod** [ThirteenAG/III.VC.SA.LimitAdjuster#23]
Can the 8 player limit be hacked in SA?

**Comment by iFarbod** [comment]
This patch allows more than 8 players:

*(BYTE *)0x60D64D = 0x90;
*(BYTE *)0x60D64E = 0xE9;

-- Token from MTA:SA Source code

**Comment by CookiePLMonster** [comment]
More arrays need to be expanded, though. Just curious, what'd you need the limit for? It's probably doable, but it really has little point in singleplayer.

**Comment by iFarbod** [comment]
So you mean can this limit be broken?

**Comment by CookiePLMonster** [comment]
What's the point?

**Comment by ifarbod** [comment]
By the way, Anyone can hack this? I Need it.
