### ISSUE TITLE
GTA VC street lights are neon coloured

### ISSUE THREAD

**Issue by IronPainting** [ThirteenAG/III.VC.SA.LimitAdjuster#34]
Streets lights and some other light sources have random colours like purple and blue and pink and stuff like that and i dont know how to fix it. other lights like headlights on a car remain intact and as usual.

**Comment by ThirteenAG** [comment]
It's a `FestiveLights` feature of Project2DFX, you can disable it like all other features or wait until january 15th when it stops working.
