### ISSUE TITLE
III.VC.SA.LimitAdjuster.asi detected as malware by Windows Defender and Virustotal

### ISSUE THREAD

**Issue by question-to-ask** [ThirteenAG/III.VC.SA.LimitAdjuster#38]
Within the last few days, Windows Defender has repeatedly detected III.VC.SA.LimitAdjuster.asi as malware, specifically "Program:Win32/Uwasson.A!ml" and Virustotal flags it under several different signs. I am assuming this is a false positive, but previous versions of this file are not flagged by Virustotal.
This is what Virustotal gives for the file: https://www.virustotal.com/gui/file/defa4dce87886f38f6fc89c0eb20fa0aac0dd391cdddd82da1ba38b4c659ad2b/details

**Comment by desumodo** [comment]
Hmmm I often see the same thing with other .asi files.. kinda scary if you ask me.

**Comment by MinePro120** [comment]
Don't worry. It's open source after all.
